# I just wanted to give taskfile.dev another try. This is optional. Get task here https://taskfile.dev/#/
# Next create a .env file
 
version: '3'
 
vars:
  GOLANGCILINT:
    sh: which golangci-lint
  GO: 
    sh: which go
  GOOS:
    sh: uname | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
  GOARCH:
    sh: uname -m
 
tasks:
  default:
    cmds:
      - task --list
    silent: true
 
  lint:
    desc: Run golangci-lint on your sourcecode
    preconditions:
      - sh: "[ '{{.GOLANGCILINT}}' != '<no value>' ]"
        msg: "golangci-lint executable not found"
    cmds:
      - |
       golangci-lint run -v
    silent: false
 
  test:
    desc: Run golangci-lint on your sourcecode
    preconditions:
      - sh: "[ '{{.GOLANGCILINT}}' != '<no value>' ]"
        msg: "golangci-lint executable not found"
    cmds:
      - |
       go test -v
    silent: false

  build:
    desc: Build binary
    preconditions:
      - sh: "[ '{{.GO}}' != '<no value>' ]"
        msg: "go executable not found"
    vars:
      VERSION: 1.0.0
    cmds:
      - |
       CGO_ENABLED=0 GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -ldflags="-X 'github.com/lukibahr/deconz-ctl/cmd.buildVersion={{.VERSION}}' -X 'github.com/lukibahr/deconz-ctl/cmd.buildCommit=$(git rev-parse --short HEAD)'" -o releases/{{.GOOS}}/{{.GOARCH}}/deconz-ctl-{{.GOARCH}} .  
    silent: false

  cleanup:
    desc: cleanup dirs
    cmds:
      - rm -rf ./releases
    silent: false
